apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-generator
  namespace: prd-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-generator
  template:
    metadata:
      labels:
        app: report-generator
    spec:
      containers:
        - name: report-generator
          image: ghcr.io/kirapixel/cm-report-generator:20251008073630
          envFrom:
            - secretRef:
                name: flask-cm-spectr-secret
